# Generated by Django 3.2.3 on 2021-05-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.CharField(max_length=4, verbose_name='Марка'),
        ),
    ]
