# Generated by Django 3.2.3 on 2021-05-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210526_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=40, verbose_name='Услуга')),
                ('name_company', models.CharField(max_length=40, verbose_name='Компания')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
    ]
