# Generated by Django 3.2.3 on 2021-05-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_addservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('telephone', models.CharField(max_length=10, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название вакансии')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('telephone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('сar_showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.carshowroom', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя клиента')),
                ('content', models.TextField(blank=True, verbose_name='Отзыв')),
                ('сar_showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.carshowroom', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
