# Generated by Django 3.2.3 on 2021-05-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carshowroom_feedback_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='telephone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='telephone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='RequestCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('telephone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.cars', verbose_name='Автомобиль')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.addservices', verbose_name='Дополнительные услуги')),
                ('сar_showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.carshowroom', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
